### ISSUE TITLE
Missing LICENSE file in the repository

### ISSUE THREAD

**Issue by alexandear** [golangci/plugin-module-register#1]
I've noticed that this repository doesn't have a LICENSE file.
A tool called [FOSSA](https://fossa.com/) also reported this issue:
<img width="714" alt="image" src="https://github.com/golangci/plugin-module-register/assets/3228886/de5c15ce-31d0-4091-944e-7a88b5060639">

**Comment by ldez** [comment]
fc0d1068b4d27b2a123ba2ec46e2d4a8bc7a389b
